[package]
name = "zed-mage"
version = "0.1.0"
authors = ["Aleksandr Kosachev <gohryt@rays-of-good.online>"]
license = "MIT"
edition = "2021"

[lib]
path = "src/mage.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
zed_extension_api = "0.7"
